### ISSUE TITLE
Fusing IMu into existing SLAM code?

### ISSUE THREAD

**Issue by antithing** [pvangoor/eqvio#1]
Hi, and thanks for making this code available. i have an existing SLAM system that I want to add IMU data to,  to both smooth the data output and allow for the imu to predict pose when features are lost for a short time.

Is this code suitable for that task?

Thanks!

**Comment by pvangoor** [comment]
Hi, eqvio is a VIO system. It provides an estimate of the robot's trajectory by using measurements from an IMU and camera. So, if you would like to generate IMU measurements to use in your SLAM system, then this code will not do that. However, if you would like to build a SLAM system that uses IMU measurements, you could build that system by using this code.

**Comment by antithing** [comment]
Understood. Thank you!
