### ISSUE TITLE
problem appeared when running kitti dataset

### ISSUE THREAD

**Issue by cll-git** [pvangoor/eqvio#10]
When I tried to run the project on KITTI, problem appeared. There were no any error or warning, but ended with:
**Processed 0 IMU and 0 vision measurements.**
(I convered the dataset to a rosbag in advance)
It seemed it had probelm with getting images. Hopping to receive any suggestion from you, thanks.

**Comment by pvangoor** [comment]
Hi @cll-git, EqVIO is only designed to be compatible with rosbags in the EuRoC format. Is this the format you used? The names of the topics is very important. Also, could you please provide the command you used to run eqvio? This will help in debugging.

**Comment by cll-git** [comment]
Sorry for replying late. I ran the code just under your guide, with an 'intrinsic.yaml' for kitti. And I wander how to set camera topic and imu topic to adapt different datasets organized as rosbag? Thanks.

**Comment by pvangoor** [comment]
Currently there is no way to handle different rosbags except by changing the C++ code of the rosbagDatasetReader.
Could you please provide the command you are using? That will help identify if there are any other issues.

**Comment by cll-git** [comment]
Noticed that you set 1 imu topic and 1 camera topic in the constructor. I just tried KITTI with imu data on VINS-Fusion, but the tractory is absolutly unstable, I guest the imu data are not useful in KITTI, so I won't try it on eqvio. Thanks for your help. and I will try different dataset on it.

**Comment by pvangoor** [comment]
Alright. In principle, the extra data should be helpful, but it does require careful calibration and tuning. If you are trying to test VIO algorithms, I recommend the UZH-FPV dataset or the EuRoC dataset, since these are very standard in the literature. Good luck!
