### ISSUE TITLE
 Initialize degradation

### ISSUE THREAD

**Issue by ZzhYgwh** [pvangoor/eqvio#3]
Hello, thank you very much for publishing this creative work. However, currently I have some development issues. When I imported data in the form of rosbag, I found that some sequences of EuRoC have degradation on EqVIO. Especially when these initializations are in motion or not strictly stationary. They don't seem to be very robust. Can you provide some improvement ideas or how to better deploy them in the operating environment of ROS?
![Screenshot from 2023-12-13 10-23-41](https://github.com/pvangoor/eqvio/assets/97495276/8e9ab7b1-a4f5-4820-9924-955d9f6a5d8b)
![Screenshot from 2023-12-13 10-22-43](https://github.com/pvangoor/eqvio/assets/97495276/6f51099f-d410-430b-9b90-a658dccffb18)

**Comment by pvangoor** [comment]
Hi, are you using the provided configuration for EuRoC? As described in the paper, this set of parameters was tuned specifically for the case of a stationary start, and we only start the machine hall datasets after the initial motion is finished. If you would like a more general set of parameters, I suggest you use the standard template rather than the EuRoC parameters. I hope this helps!

**Comment by ZzhYgwh** [comment]
Thank you very much for your reply! I am indeed using **EQVIO_config_EuRoC_stationary.yaml**  The configuration parameters in stationary.yaml. It is indeed a set of parameters that only apply to static initial conditions. If I want to try to replicate the experimental results of EuRoC in the paper, I need to skip the motion phase. So I used 
```
./eqvio_opt /home/hao/Desktop/dataset/V1_03/MH_01_easy.bag ../configs/EQVIO_config_EuRoC_stationary.yaml --mode ros --start 23 --camera /home/hao/Desktop/dataset/V1_03/intrinsics.yaml --display
```
result is like this:
![Screenshot from 2023-12-13 16-30-06](https://github.com/pvangoor/eqvio/assets/97495276/b7101fb4-98f4-4561-a748-3a9a26e24b25)
It seems to be working normally. Thank you!

**Comment by pvangoor** [comment]
I'm glad to see it's working. Thanks for letting me know and good luck with your application!
