### ISSUE TITLE
Check results

### ISSUE THREAD

**Issue by bromotdi** [pvangoor/eqvio#6]
I can run the code with:

./build/eqvio_opt  ./data/MH_03_medium.bag configs/EQVIO_config_EuRoC_stationary.yaml --display --mode ros

However, is there a way to compare the results with ground truth from bag?

**Comment by pvangoor** [comment]
Hi @bromotdi, I recommend the toolbox https://github.com/uzh-rpg/rpg_trajectory_evaluation
You may need to reformat some of the EqVIO output a little, but it should not be too difficult.
