### ISSUE TITLE
Fisheye Camera

### ISSUE THREAD

**Issue by bromotdi** [pvangoor/eqvio#7]
Hi! Do you test it on fisheye camera? Does it possible?

**Comment by pvangoor** [comment]
Hi @bromotdi, no I have not tested on fisheye cameras. In principle, you would just need to change the feature tracking camera model, which should be possible using GIFT. You can see the different camera models already implemented here: https://github.com/pvangoor/GIFT/tree/master/GIFT/include/GIFT/camera

**Comment by bromotdi** [comment]
Thanks a lot !!
