### ISSUE TITLE
uzhfpv dataset

### ISSUE THREAD

**Issue by yuanliu0015** [pvangoor/eqvio#8]
Hello! I've recently been learning EqVIO and encountered a problem. When running the EuRoC dataset, it was successful, but when I switched to the UZH-FPV dataset, the operation failed, as if no data was being received at all. I'm wondering what might be causing this issue? Is there a need to modify any part of the code? Thank you very much!

**Comment by pvangoor** [comment]
Hi @yuanliu0015, sorry for the late response. Were you able to resolve your issue?

**Comment by yuanliu0015** [comment]
Hello! I have solved my problem. This is a great job! Thank you very much!
