### ISSUE TITLE
Custom setup configuration

### ISSUE THREAD

**Issue by korizona** [pvangoor/eqvio#9]
Dear @pvangoor,

Thank you very much for your code and contribution. I think it's a very thorough contribution to the SLAM community. 

I have successfully run your code on the EuROC & UZHFPV dataset in my computer. Now, i wanted to use your code on my custom dataset which consists of Image and IMU coming from Realsense D435i and MTI-30 IMU, respectively. However, i ran into some problem because the result was not as what i expected since i thought the configurations are similar to EuROC. I understand that there would be extrinsic changes and i have adapted it accordingly.

Therefore, i want to ask, **how did you determine the other configuration values such as initial variance, measurement noise, and etc?** I would be grateful for your help and answer.

Cheers!

**Comment by pvangoor** [comment]
Hi @korizona,
When I was working on the development, I tested on EuRoC so I tuned the parameters for this. These parameters worked reasonably well on most other things I tried, so the parameters for UZHFPV were based on them.
As you say, the extrinsics (but also the intrinsics) have to be carefully calibrated and set. After this, however, it is a matter of tuning carefully. It depends on the problem you are having for me to be able to give more advice. If you are getting a lot of flashing points in the visualisation, this indicates that the outlier rejection thresholds are set too low, or the measurement variance too small. The most important parameters to tune are usually those related to the measurement and process uncertainty. The initial variance parameters tend not to have a large impact on the long-term performance.

Let me know if you have any more specific questions, and I would be happy to help!
